/**
 * interrupted-run support.
 *
 * when a deploy restarts dude-wait.service, systemd SIGTERMs the whole
 * cgroup and an in-flight agent run dies mid-work. recovery has three
 * pieces (all written on SIGTERM, before the agent exits):
 *
 *   1. session marker: an `interrupted` custom entry appended to the pi
 *      session jsonl, so the transcript says "this session ended
 *      abnormally" instead of just stopping mid-message.
 *   2. breadcrumb (~/.config/dude/interrupted.json): { ts, reason,
 *      sessionFile, purpose }. `dude-agent --resume-interrupted` opens
 *      this session and tells the model to finish/close out the prior
 *      run's half-done work.
 *   3. a resume ONE-SHOT wait function in wait-functions.d/ (fixed name
 *      so re-kills overwrite rather than pile up): fires the next tick
 *      with --resume-interrupted, self-deletes if the breadcrumb is gone
 *      or TTL-expired (24h) so a crash loop can't accumulate corpses.
 */

import fs from "fs";
import path from "path";

export const RESUME_ONESHOT_TTL_MS = 24 * 60 * 60 * 1000;
export const RESUME_ONESHOT_NAME = "resume-interrupted";

export function breadcrumbFile(configDir = process.env.DUDE_CONFIG_DIR || path.join(process.env.HOME || "/tmp", ".config/dude")) {
  return path.join(configDir, "interrupted.json");
}

export function userFunctionsDir() {
  return process.env.DUDE_WAIT_USER_FUNCTIONS_DIR ||
    path.join(
      process.env.DUDE_CONFIG_DIR || path.join(process.env.HOME || "/tmp", ".config/dude"),
      "wait-functions.d",
    );
}

/** write the interrupted breadcrumb. returns the breadcrumb object. */
export function writeBreadcrumb({ reason, sessionFile, purpose = null, configDir } = {}) {
  const file = breadcrumbFile(configDir);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const bc = {
    ts: new Date().toISOString(),
    reason: String(reason || "unknown"),
    sessionFile: sessionFile || null,
    purpose: purpose || null,
  };
  fs.writeFileSync(file, JSON.stringify(bc, null, 2));
  return bc;
}

/** read the breadcrumb; null when missing/corrupt/stale past TTL. */
export function readBreadcrumb({ configDir, ttlMs = RESUME_ONESHOT_TTL_MS, now = Date.now() } = {}) {
  try {
    const bc = JSON.parse(fs.readFileSync(breadcrumbFile(configDir), "utf8"));
    if (!bc || typeof bc.ts !== "string" || now - Date.parse(bc.ts) > ttlMs) return null;
    return bc;
  } catch {
    return null;
  }
}

/** delete the breadcrumb (the resume path consumes it). */
export function clearBreadcrumb(configDir) {
  try { fs.unlinkSync(breadcrumbFile(configDir)); } catch { /* gone */ }
}

/**
 * write the resume one-shot wait function. fixed name → at most one
 * pending resume; a newer kill overwrites the older one. returns the
 * path written.
 */
export function writeResumeOneShot({ reason, ts, sessionFile, purpose = null, dir = userFunctionsDir(), configDir } = {}) {
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `${RESUME_ONESHOT_NAME}.js`);
  const ctx = `previous agent run was interrupted by ${reason} at ${ts}; resume that session, verify any half-finished work (uncommitted files, open PRs, task-doc notes), and finish or cleanly close it out`;
  const body = `// AUTO-GENERATED by a SIGTERM-interrupted agent run (${ts}). one-shot:
// fires the next wait tick with --resume-interrupted, then retires.
export const oneshot = true;
export const purpose = null;
export const args = ["--resume-interrupted"];

import fs from "fs";
import path from "path";

const BREADCRUMB = ${JSON.stringify(breadcrumbFile(configDir))};
const TTL_MS = ${RESUME_ONESHOT_TTL_MS};
const MY_NAME = ${JSON.stringify(RESUME_ONESHOT_NAME)};

export async function check() {
  let bc = null;
  try { bc = JSON.parse(fs.readFileSync(BREADCRUMB, "utf8")); } catch { /* none */ }
  const expired = !bc || typeof bc.ts !== "string" || Date.now() - Date.parse(bc.ts) > TTL_MS;
  if (expired) {
    // nothing to resume: retire quietly instead of firing an idle run
    try { fs.unlinkSync(path.join(${JSON.stringify(dir)}, MY_NAME + ".js")); } catch { /* gone */ }
    return { fire: false, state: { retired: true } };
  }
  // consume the breadcrumb; if this resume run is itself killed, the
  // SIGTERM handler writes a fresh breadcrumb + oneshot
  try { fs.unlinkSync(BREADCRUMB); } catch { /* gone */ }
  return { fire: true, context: ${JSON.stringify(ctx)}, state: { resumedAt: new Date().toISOString() } };
}
`;
  fs.writeFileSync(file, body);
  return file;
}

/** prompt used when a run resumes an interrupted session. */
export function buildResumePrompt(breadcrumb, now = new Date()) {
  return `Current date: ${now.toLocaleString("en-US")}

your previous run was interrupted (SIGTERM, almost certainly a deploy restarting dude-wait.service) at ${breadcrumb?.ts ?? "unknown time"}. you have been resumed into that session's transcript: everything above is YOUR OWN prior context.

first order of business:
- read the transcript above and figure out exactly where you were killed mid-work
- look for half-finished state: uncommitted edits, feature branches, open PRs, half-edited task docs, stray temp files in the workspace
- either finish that work properly, or roll it back / leave a clean note explaining what's left
- when done, log a one-line "recovered from interruption" note in the usual places

do not start brand-new tasks before closing out the interrupted work.`;
}
