name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  propose-vps-update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GH_TOKEN: "op://dude GHA SA/dudeagent-github-pat/token"

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: make branch + update + commit + push
        run: |
          gh repo clone johndikeman/dotfiles 
          cd dotfiles 
          git checkout vps_nix 
          git checkout -b update-dude-${{github.sha}} 
          nix flake update dude 
          git add flake.lock 
          git config --global user.email "dude@johnf.art"
          git config --global user.name "dude"
          git commit -m "chore: update dude to ${{github.sha}}" 
          gh auth setup-git
          git push origin update-dude-${{github.sha}}
      - name: open pr
        run: |
          cd dotfiles
          gh pr create -B vps_nix --fill
